export const CREATE_MEETUP = "CREATE_MEETUP";
export const RETRIEVE_MEETUPS = "RETRIEVE_MEETUPS";
export const UPDATE_MEETUP = "UPDATE_MEETUP";
export const DELETE_MEETUP = "DELETE_MEETUP";
export const SELECT_MEETUP = "SELECT_MEETUP";
